Добавление регистрации пользователей
DKeysil/mandatory-contribution pull request #6
Opened 2021-05-01 12:01 UTC by DavisDmitry

2021-05-02 13:18 UTC, DKeysil requested changes

2021-05-02 13:18 UTC, DKeysil commented on bot/users/filters.py
> +        if await db.models.User.get({'tg_id': int(obj.from_user.id)}):
Надо сделать метод get_user_by_tg_id в модели юзера

А лучше сделать по паттерну Repository (типо отдельный класс под подобные методы)

2021-05-02 13:18 UTC, DKeysil commented on bot/users/middlewares.py
> +        if user:
Так как это только BanMiddleware, думаю моэно сделать так:
```
if user and user.get('banned'):
```
А вообще тут тоже юзера надо получать по get_tg_id и не возвращать None по заветам этого мужика https://www.youtube.com/watch?v=QwycPnpp6uQ

2021-05-02 13:18 UTC, DKeysil commented on bot/users/registration.py
> +async def start_cmd(msg: types.Message, state: FSMContext):
имхо, я бы все названия функция тут именовал как `something_handler` (ты так вроде делал уже, когда нет декоратора это добавит понимания, хоят бы, что это хэндлеры)

2021-05-02 13:29 UTC, DavisDmitry commented on bot/users/middlewares.py
> +        if user:
Ну миддлварь вроде как не может что-то возвращать.

2021-05-02 13:33 UTC, DavisDmitry commented on bot/users/registration.py
> +async def start_cmd(msg: types.Message, state: FSMContext):
Тут надо подумать. Вроде бы понятно, что может быть хендлером по передаваемым аргументам. Может стоит докстринги дописать.

2021-05-02 13:34 UTC, DKeysil commented on bot/users/middlewares.py
> +        if user:
Я про то, что переменная user может быть None, надо избавляться от такого и рэйзить эксепшн

2021-05-05 12:38 UTC, DKeysil commented on bot/users/registration.py
> +async def start_cmd(msg: types.Message, state: FSMContext):
Ну блин, мне все равно не нравится, что у тебя перемешаны обычные функции и хэндлеры и отличить их можно только док стрингом :/ (ладно, еще можно по аргументам отличить, но блиин)

Ты действительно считаешь, что названия функций станут отвратительными, если добавить handler?

2021-05-06 09:39 UTC, DavisDmitry commented on bot/users/registration.py
> +async def start_cmd(msg: types.Message, state: FSMContext):
> Ты действительно считаешь, что названия функций станут отвратительными, если добавить handler?

Ну хендлеры тут выполняют какую-то функцию, кроме того, что они хедлеры. Тут либо отделять функцию от просто хендлера, то есть добавлять ещё один слой, либо просто пересматривать нейминг, но станет менее понятно назначение функции.

2021-05-06 09:42 UTC, DKeysil commented on bot/users/registration.py
> +async def start_cmd(msg: types.Message, state: FSMContext):
Тогда можно обратиться к clean code где функция вообще не должна выполнять больше одной функции :P
но это заеб, поэтому я пока против такого..

2021-05-06 09:44 UTC, DKeysil commented on bot/users/registration.py
> +async def start_cmd(msg: types.Message, state: FSMContext):
Типо, это сейчас и так хэндлер. От того, что добавить туда нейминг, что это хэндлер он от этого уже не станет, как мне кажется. То есть ты и так написал в докстрингах что это хэндлер ы

5 дней спорить по поводу нейминга это сильно конечно :D

2021-05-06 18:08 UTC, merged