add other models, refactor models tests
DKeysil/mandatory-contribution pull request #8
Opened 2021-05-23 15:12 UTC by DKeysil

в схеме contribution изменил `requisites` на `requisites_id`
В payment изменил `real_payer_region` на `real_payer_region_id`, `requisite` на `requisite_id`

сделал рефактор тестов, добавил оставшиеся модели и методы для них

2021-05-23 16:25 UTC, DavisDmitry requested changes

2021-05-23 16:25 UTC, DavisDmitry commented on core/db/models/models.py
> +from bson.objectid import ObjectId
А зачем так?

2021-05-23 16:25 UTC, DavisDmitry commented on core/db/models/models.py
> +        if isinstance(contribution_id, ObjectId):
Зачем делать проверку, если можно просто конвертировать. Если это и так ObjectId, то он им и останется

2021-05-23 23:50 UTC, DKeysil commented on core/db/models/models.py
> +from bson.objectid import ObjectId
Думаю я автоимпортнул, мб лучше поменять на `from bson import ObjectId`, будет лучше

2021-05-23 23:50 UTC, DKeysil commented on core/db/models/models.py
> +        if isinstance(contribution_id, ObjectId):
По факту, исправлю

2021-05-24 07:42 UTC, DavisDmitry commented on core/db/models/models.py
> +from bson.objectid import ObjectId
> Думаю я автоимпортнул, мб лучше поменять на `from bson import ObjectId`, будет лучше

Ну типа рекомендуется импортировать модуль, а не объекты из него, но для часто используемый классов делают исключения (например из typing). Ну хз насколько сложно дописывать 5 символов..

2021-05-24 16:59 UTC, merged